"""Regenerate src/emoji_shortcodes.rs from GitHub's gemoji database.

Usage (development time only; the renderer never fetches anything):

    curl -fsSL -o emoji.json https://raw.githubusercontent.com/github/gemoji/master/db/emoji.json
    curl -fsSL -o LICENSE https://raw.githubusercontent.com/github/gemoji/master/LICENSE
    python3 -I scripts/generate-emoji-shortcodes.py emoji.json LICENSE

Only Unicode emoji are kept (gemoji's custom GitHub images have no
character). The table is sorted by alias for binary search, and every emoji
is written as `\\u{...}` escapes so the source stays plain ASCII.
"""
from pathlib import Path
import json
import re
import sys

if len(sys.argv) != 3:
    raise SystemExit("usage: generate-emoji-shortcodes.py EMOJI_JSON LICENSE")
entries = json.loads(Path(sys.argv[1]).read_text(encoding="utf-8"))
license_text = Path(sys.argv[2]).read_text(encoding="utf-8").strip()
if "Permission is hereby granted" not in license_text:
    raise SystemExit("expected gemoji's MIT license text")

aliases = {}
for entry in entries:
    emoji = entry.get("emoji")
    if not emoji:
        continue
    for alias in entry.get("aliases", []):
        if not re.fullmatch(r"[a-z0-9_+\-]{1,40}", alias):
            raise SystemExit(f"unexpected alias shape: {alias!r}")
        aliases.setdefault(alias, emoji)

def escape(value):
    return "".join(f"\\u{{{ord(ch):X}}}" for ch in value)

rows = "\n".join(f'    ("{alias}", "{escape(emoji)}"),' for alias, emoji in sorted(aliases.items()))
license_comment = "\n".join(f"// {line}".rstrip() for line in license_text.splitlines())
out = f"""// Generated by scripts/generate-emoji-shortcodes.py. Do not edit the table.
// GitHub emoji shortcodes (`:rocket:`) from github/gemoji db/emoji.json,
// Unicode emoji only, sorted by alias for binary search.
//
// gemoji is distributed under the MIT license:
//
{license_comment}

/// `(alias, emoji)` pairs sorted by alias.
pub(crate) static SHORTCODES: &[(&str, &str)] = &[
{rows}
];

/// The emoji for a shortcode alias (the text between the colons).
pub(crate) fn lookup(alias: &str) -> Option<&'static str> {{
    SHORTCODES
        .binary_search_by(|(name, _)| (*name).cmp(alias))
        .ok()
        .map(|index| SHORTCODES[index].1)
}}
"""
Path("src/emoji_shortcodes.rs").write_text(out, encoding="ascii")
print(f"wrote src/emoji_shortcodes.rs with {len(aliases)} aliases")
