"""Regenerate the browser reader's frozen Unicode 15.1 default full case folding.

Requires a Python with unicodedata 15.1.0 (e.g. Python 3.13). This uses only
Python's Unicode database at development time; no Python/runtime dependency
is added to the renderer. Source data: Unicode CaseFolding.txt, C+F mappings,
excluding Turkic tailoring. Verify the emitted module against str.casefold on
all Unicode scalars when changing its representation.
"""
from pathlib import Path
import json
import unicodedata

VERSION = "15.1.0"
if unicodedata.unidata_version != VERSION:
    raise SystemExit(f"Expected Unicode {VERSION}; found {unicodedata.unidata_version}")
pairs = [(cp, chr(cp).casefold()) for cp in range(0x110000)
         if not 0xD800 <= cp <= 0xDFFF and chr(cp).casefold() != chr(cp)]
singles = [(cp, ord(value) - cp) for cp, value in pairs if len(value) == 1]
ranges = []
i = 0
while i < len(singles):
    cp, delta = singles[i]
    end, stride = i + 1, 1
    for step in (1, 2):
        j = i + 1
        while (j < len(singles) and singles[j][0] == singles[j - 1][0] + step
               and singles[j][1] == delta):
            j += 1
        if j > end:
            end, stride = j, step
    ranges.append((cp, singles[end - 1][0], stride, delta))
    i = end
header = '''// Generated by scripts/generate-reading-casefold.py. Do not edit the tables.
// Frozen Unicode 15.1.0 default FULL (C+F, non-Turkic) case folding.
// Not normalization, accent removal, transliteration, or locale-sensitive casing.
// https://www.unicode.org/Public/15.1.0/ucd/CaseFolding.txt
/*
UNICODE LICENSE V3
Copyright © 1991-2026 Unicode, Inc.

NOTICE TO USER: Carefully read the following legal agreement. BY
DOWNLOADING, INSTALLING, COPYING OR OTHERWISE USING DATA FILES, AND/OR
SOFTWARE, YOU UNEQUIVOCALLY ACCEPT, AND AGREE TO BE BOUND BY, ALL OF THE
TERMS AND CONDITIONS OF THIS AGREEMENT. IF YOU DO NOT AGREE, DO NOT
DOWNLOAD, INSTALL, COPY, DISTRIBUTE OR USE THE DATA FILES OR SOFTWARE.
Permission is hereby granted, free of charge, to any person obtaining a
copy of data files and any associated documentation (the "Data Files") or
software and any associated documentation (the "Software") to deal in the
Data Files or Software without restriction, including without limitation
the rights to use, copy, modify, merge, publish, distribute, and/or sell
copies of the Data Files or Software, and to permit persons to whom the
Data Files or Software are furnished to do so, provided that either (a)
this copyright and permission notice appear with all copies of the Data
Files or Software, or (b) this copyright and permission notice appear in
associated Documentation.
THE DATA FILES AND SOFTWARE ARE PROVIDED "AS IS", WITHOUT WARRANTY OF ANY
KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT OF
THIRD PARTY RIGHTS.
IN NO EVENT SHALL THE COPYRIGHT HOLDER OR HOLDERS INCLUDED IN THIS NOTICE
BE LIABLE FOR ANY CLAIM, OR ANY SPECIAL INDIRECT OR CONSEQUENTIAL DAMAGES,
OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS,
WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION,
ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THE DATA
FILES OR SOFTWARE.
Except as contained in this notice, the name of a copyright holder shall
not be used in advertising or otherwise to promote the sale, use or other
dealings in these Data Files or Software without prior written
authorization of the copyright holder.
*/
export const CASE_FOLD_VERSION = "15.1.0";
// [first, last, stride, delta]; sorted non-overlapping inclusive ranges.
const RANGES = [
'''
rows = [f"  [0x{lo:x}, 0x{hi:x}, {step}, {delta}]," for lo, hi, step, delta in ranges]
full = [f"  [0x{cp:x}, {json.dumps(value, ensure_ascii=True)}]," for cp, value in pairs if len(value) != 1]
tail = '''
// Input is one already-admitted Unicode scalar, never an arbitrary string.
export function foldScalar(cp) {
  if (cp < 128) return String.fromCodePoint(cp >= 65 && cp <= 90 ? cp + 32 : cp);
  const expansion = EXPANSIONS.get(cp);
  if (expansion !== undefined) return expansion;
  let low = 0, high = RANGES.length;
  while (low < high) {
    const mid = (low + high) >>> 1, [first, last, stride, delta] = RANGES[mid];
    if (cp < first) high = mid;
    else if (cp > last) low = mid + 1;
    else return String.fromCodePoint((cp - first) % stride === 0 ? cp + delta : cp);
  }
  return String.fromCodePoint(cp);
}
'''
output = header + "\n".join(rows) + "\n];\nconst EXPANSIONS = new Map([\n" + "\n".join(full) + "\n]);\n" + tail
path = Path(__file__).resolve().parents[1] / "wasm/flow_reading.mjs"
start_marker, end_marker = "// BEGIN GENERATED CASE FOLDING\n", "// END GENERATED CASE FOLDING\n"
source = path.read_text(encoding="utf-8")
if source.count(start_marker) != 1 or source.count(end_marker) != 1:
    raise SystemExit("Expected exactly one generated case-folding region")
start = source.index(start_marker) + len(start_marker)
end = source.index(end_marker, start)
path.write_text(source[:start] + output + source[end:], encoding="utf-8")
print(f"{len(pairs)} mappings, {len(ranges)} ranges, {len(full)} expansions: {path}")
