"""Regenerate src/emoji_shortcodes.rs from GitHub's gemoji database.

Usage (development time only; the renderer never fetches anything):

    curl -fsSL -o emoji.json https://raw.githubusercontent.com/github/gemoji/master/db/emoji.json
    curl -fsSL -o LICENSE https://raw.githubusercontent.com/github/gemoji/master/LICENSE
    python3 -I scripts/generate-emoji-shortcodes.py emoji.json LICENSE

Only Unicode emoji are kept (gemoji's custom GitHub images have no
character). The table is sorted by alias for binary search, and every emoji
is written as `\\u{...}` escapes so the source stays plain ASCII.
"""
from pathlib import Path
import json
import re
import sys

if len(sys.argv) != 3:
    raise SystemExit("usage: generate-emoji-shortcodes.py EMOJI_JSON LICENSE")
entries = json.loads(Path(sys.argv[1]).read_text(encoding="utf-8"))
license_text = Path(sys.argv[2]).read_text(encoding="utf-8").strip()
if "Permission is hereby granted" not in license_text:
    raise SystemExit("expected gemoji's MIT license text")

aliases = {}
for entry in entries:
    emoji = entry.get("emoji")
    if not emoji:
        continue
    for alias in entry.get("aliases", []):
        if not re.fullmatch(r"[a-z0-9_+\-]{1,40}", alias):
            raise SystemExit(f"unexpected alias shape: {alias!r}")
        aliases.setdefault(alias, emoji)

def escape(value):
    return "".join(f"\\u{{{ord(ch):X}}}" for ch in value)

# One table entry per source line; a trailing backslash continues the literal.
lines = "\\\n".join(f"{alias}\\t{escape(emoji)}\\n" for alias, emoji in sorted(aliases.items()))
license_comment = "\n".join(f"// {line}".rstrip() for line in license_text.splitlines())
out = f"""// Generated by scripts/generate-emoji-shortcodes.py. Do not edit the table.
// GitHub emoji shortcodes (`:rocket:`) from github/gemoji db/emoji.json,
// Unicode emoji only.
//
// gemoji is distributed under the MIT license:
//
{license_comment}

/// One `alias\\temoji\\n` line per shortcode, sorted by alias. A single
/// string (no per-entry pointers) keeps the table about half the size of a
/// slice of pairs; lookups binary-search line starts by byte offset.
static TABLE: &str = "\\\n{lines}";

/// The emoji for a shortcode alias (the text between the colons).
pub(crate) fn lookup(alias: &str) -> Option<&'static str> {{
    let bytes = TABLE.as_bytes();
    let (mut low, mut high) = (0usize, bytes.len());
    while low < high {{
        let mid = low + (high - low) / 2;
        // Snap to the start of the line containing `mid`. Newlines are ASCII,
        // so line bounds are always char boundaries even inside emoji bytes.
        let start = bytes[..mid]
            .iter()
            .rposition(|&byte| byte == b'\\n')
            .map_or(0, |newline| newline + 1);
        let end = bytes[start..]
            .iter()
            .position(|&byte| byte == b'\\n')
            .map_or(bytes.len(), |offset| start + offset);
        let (name, emoji) = TABLE[start..end].split_once('\\t')?;
        match name.cmp(alias) {{
            std::cmp::Ordering::Equal => return Some(emoji),
            std::cmp::Ordering::Less => low = end + 1,
            std::cmp::Ordering::Greater => high = start,
        }}
    }}
    None
}}

#[cfg(test)]
mod tests {{
    #[test]
    fn every_alias_round_trips_and_misses_are_none() {{
        for line in super::TABLE.lines() {{
            let (alias, emoji) = line.split_once('\\t').unwrap_or_default();
            assert_eq!(super::lookup(alias), Some(emoji), "{{alias}}");
        }}
        for miss in ["", "zzzz", "+0", "rocke", "rocketx", "ROCKET"] {{
            assert_eq!(super::lookup(miss), None, "{{miss}}");
        }}
    }}
}}
"""
Path("src/emoji_shortcodes.rs").write_text(out, encoding="ascii")
print(f"wrote src/emoji_shortcodes.rs with {len(aliases)} aliases")
